[workspace]
independent = false

[release]
publish = true
publish-order = "depth"
tag = true
push = true
verify = true

# Make sure version in Cargo.toml is updated everywhere
consolidate-workspace-versions = true

# Add a delay between each publish to allow crates.io to update
# Helps avoid "dependency not found" errors
delay-publish = 10

# Workaround for circular dependencies if needed
# allow-branch = ["main", "release/*"]

# Customize pre-release hooks if needed
# pre-release-hook = "./scripts/pre_release.sh"
